# Generated by Django 2.2.3 on 2019-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('paid', 'Paid')], default='created', max_length=120)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=1500.99, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cart', models.ForeignKey(on_delete=False, to='carts.Cart')),
            ],
        ),
    ]
